### ISSUE TITLE
Autoplay for youtube-nocookie.com videos

### ISSUE THREAD

**Issue by Grienauer** [jonnitto/Jonnitto.PrettyEmbedVideoPlatforms#1]
I am a fan of using youtube-nocookie.com, but currently I am running into an issue, that it is not possible to pass the parameter "&autoplay=1".

So a user needs to click two times to start a video.

Demo url: with some other parameters, which work (except of autoplay): https://www.youtube-nocookie.com/embed/vwq9_rO28us?&autoplay=1&start=41&end=56&fs=0&controls=2&modestbranding=1&playsinline=1&rel=0&showinfo=0

**Describe the solution you'd like**
If I click the preview Image, the iframe which will be then load, should automatically start.

**Describe alternatives you've considered**
have an option to switch to the default youtube url, if the video has to load automatically. (maybe the consent element has to be shown then #gdpr, if no consent has given before via cookie)

**Comment by jonnitto** [comment]
Closed with version 6, as it uses the iframe API
