### ISSUE TITLE
Autoplay with Firefox on mobile Devices

### ISSUE THREAD

**Issue by Schuppel1** [jonnitto/Jonnitto.PrettyEmbedVideoPlatforms#5]
**The autoplay function on mobile devices does not work with Firefox**
Firefox blocks all autoplay videos with sound.  
To be sure Firefox settings are not the problem I set the settings from Firefox to "Allow Audio and Video"

For reference:   
https://codepen.io/nagasai/pen/mdEZabp  
a native implementation was working with autoplay on my smartphone with firefox. 

I also tested Safari, Chrome and Samsung Browser. No Problem

**Information**
This bug appears only on smartphones. The error does not appear in compatibility mode. 

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy Note 20
- OS: Android 13
- Browser: Firefox
- Version 118.2.0

**Comment by jonnitto** [comment]
I'm currently working on a new version: Can you check this with this link: 
https://assets.uhlmann.pro/prettyembed/

**Comment by Schuppel1** [comment]
> I'm currently working on a new version: Can you check this with this link: https://assets.uhlmann.pro/prettyembed/

(Tested with Smarthphone from comment above)
Firefox Version is updated to 120.0.2

Autoplay worked. 
I checked the rest on mobile device too. All worked fine
